version: '3.8'
services:
  db:
    image: postgres:15
    container_name: tasks_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
